### ISSUE TITLE
Is there a way to keep git history?

### ISSUE THREAD

**Issue by marcomicera** [QMSTR/builder#3]
When generating a repository from a [GitHub template](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository), the generated repo only has 1 "Initial commit". Is there a way to avoid this?

**Comment by somayeh-najafi** [comment]
@marcomicera According Github docs templating is supposed to act like that, it doesn't keep the history of commits.

[https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template#about-repository-templates](url)

**Comment by marcomicera** [comment]
Ok! Closing.
